#!/bin/sh
set -e
set -u
for arg; do
    case "$arg" in
        -?*) ;;
        *)
            rarg="$(realpath "$arg")"
            case "$rarg" in
                /|/usr|/var|/etc|/home|/bin|/lib|/lib64|/boot|/opt|/media|/mnt|/root)
                    echo "NOT REMOVING $rarg" 1>&2
                    exit 100
                    ;;
            esac
            ;;
    esac
done
exec /bin/rm --one-file-system --preserve-root "$@"
