---
- name: install packages
  package: name="{{ item }}" state=latest
  with_items:
    - terminator
    - guake
- name: Ubuntu stuff
  when: ansible_distribution == 'Ubuntu'
  include: ./ubuntu.yml
- name: Archlinux stuff
  when: ansible_distribution == 'Archlinux'
  include: ./archlinux.yml
